# Generated by Django 6.1 on 2026-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='harvest_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='quantity_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
